### ISSUE TITLE
Capture unapplied mainnet tweaks

### ISSUE THREAD

**Issue by Shadowfiend** [keep-network/tbtc-dapp#297]
We've got a few tweaks that we applied on mainnet in #210 that didn't bubble back to the main branch. Let's make sure these tweaks, or the appropriate adaptations based on the current dApp, land on the main branch. Following is a list.

- [x] Handling mainnet config (https://github.com/keep-network/tbtc-dapp/commit/f1536a829bcd55f59f8fa4f94944d1c604c6dff9). Ideally, this would be a toggle we'd make based on the Ropsten chain id (see #205 for some initial work in this dept). -> see #352 
- [x] Clarifying that funding should not happen from an exchange (https://github.com/keep-network/tbtc-dapp/pull/210/commits/ff5c294e6917023d713390cfa9d3da58bf56bf0a). -> see #352 
- [x] Call out the exact nature of the expected BTC payment (https://github.com/keep-network/tbtc-dapp/commit/8dffb7d4d5608a1072e9e2f16a13b0ff9007f5d3). -> see #352 
- [ ] Clarify how many Bitcoin confirmations we are waiting for (https://github.com/keep-network/tbtc-dapp/commit/63dbad8750864ab13e333b35f625de768fef5c6a). This should live in [the `Confirming` component](https://github.com/keep-network/tbtc-dapp/blob/master/src/components/deposit/Confirming.js#L24). Ideally we would read the confirmation count from the constants contract, and track how many confirmations we've already observed, but that's likely best served by a separate issue.

Remaining commits on that branch have either been obsoleted or applied.
